config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get    'tweets/history'=> 'tweets#history'
  get    'tweets/tool'=>'tweets#tool'
  get    'tweets/drink'=>'tweets#drink'
  resources :tweets
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sado</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <header>
      <h1>sado</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", tweets_path %></li>
        <li><%= link_to "歴史",tweets_history_path %></li>
        <li><%= link_to "道具",tweets_tool_path %></li>
        <li><%= link_to "飲み方",tweets_drink_path %></li>
      </ul>
      </div>
    </header>

<main>
<%= yield %>
</main>
  </body>
</html>

app/views/tweets/drink.html.erb
<!--   First block Start   -->
  <section id="first-block2">
    <div class="title-container">
      <h1>茶道江戸千家の世界</h1>
      <h3>~ Geeksalon Webコース1期生 ~</h3>
    </div>
  </section>
  <!--   First block End   -->
  <!--   Second block Start   -->
  <section id="second-block">
    <p class="info-title">
        About me
    </p>
    <div class="about-container">
      <p class="info-text">
        <b>あいさつ・茶碗の移動</b>
        <br>
        <span class="font-small">
正客は茶碗を次客との間に置く。畳の縁内に。
正客：「おさきに」
と次客に行のおじぎをする。
次客：「どうぞ」
とおじぎをする。
茶碗を正面に置いてお茶を点てた方にごあいさつをする。
「お点前ちょうだいいたします」
と真のおじぎ。

次客がいただく時は、畳の縁内、正客との間に置いて、
「お相伴いたします」
と行のおじぎをする。次客以降の方が上座の方へするごあいさつ。
三客には「おさきに」とごあいさつ。「ご相伴」はご一緒するという意味。
        </span>
        <image src="/assets/rectangle_large_type_2_fa601d34ab5e88626ef608887291c1d4.webp" class="garden2-image"width="300">
      </p>

      <p class="info-text">
        <b>お茶の飲み方</b>
        <br>
        <span class="font-small">
        １．右手で横からお茶碗を持ち、左手の上にのせる。２．右手の親指を手前にして横から添える。感謝の気持ちを込める。（ここ一礼したか次の時確認）３．お茶碗を右手で横から持ち、横から手前、横から手前と2回時計回りに茶碗を回す。４．右手を横から添えて（写真↑みたいに）、お茶をいただく。最後の1口は「ズッ」と音をたてる。吸い切りという。５．親指と人差し指で飲み口を清め（拭き）、指先をお菓子をいただいた際に使った懐紙で拭く。６．手前から横、手前から横とお茶碗を反時計回りにまわし正面の向きを戻す。７．右手で横から持ち（親指が上）、畳の縁外に置く。
        <br>
        <image src="/assets/inside_gate2.jpg" class="inside_gate2-image">
      </p>

      
      <p class="info-text">
        <b>茶碗の拝見の仕方</b>
        <br>
        <span class="font-small">
        「拝見させていただきます」と真のおじぎをする。（あいさつの言葉次の時確認）上から全体を拝見し、そのあと両肘を畳について持ち上げ、側面や裏など細部まで見ます。背面には作り手の名前が書かれているのでそれも確認。
        <br>
        <image src="/assets/iemoto.jpg" class="iemoto-image">
      </p>


    
    

app/views/tweets/history.html.erb
<!--   First block Start   -->
  <section id="first-block2">
    <div class="title-container">
      <h1>茶道江戸千家の世界</h1>
      <h3>~ Geeksalon Webコース1期生 ~</h3>
    </div>
  </section>
  <!--   First block End   -->
  <!--   Second block Start   -->
  <section id="second-block">
    <p class="info-title">
        About me
    </p>
    <div class="about-container">
      <p class="info-text">
        <b>初代　川上不白</b>
        <br>
        <span class="font-small">
        川上不白（享保四年～文化四年　九十歳）は紀州の新宮で生れ、紀伊藩江戸詰家老水野家の家臣として江戸に出ます。将軍吉宗による紀伊の勢力を背景に、京都へ茶の湯の修業に送られ、表千家の七代如心斎の元で修業を重ねて千家流の茶人になりました。
        <br>
        江戸に帰任して紀伊藩の茶頭としての仕事を務めます。この時季、上方から江戸へという経済や文化の流れのなかで、武家社会とそれに連なる町人社会に茶道を広めました。
        <br>
        また不白自身、江戸の町人文化の影響を受けながら京都とはまた違った江戸前の茶風をつくりあげました。
        </span>
        <image src="/assets/garden2.jpg" class="garden2-image">
      </p>

      <p class="info-text">
        <b>七代  蓮々斎</b>
        <br>
        <span class="font-small">
        流祖不白の家系を継ぐ江戸末期から明治の人。維新とともに代々続いた紀伊藩水野家の茶頭職の地位を離れ、故郷新宮に帰ります。
        <br>
        明治の初年に東京に戻り、やがてこの池之端の地に茶家を復興しました。そして文明開化から日本の伝統文化が見直されるなかで、徐々に門人を増やしてゆきました。谷中にある流祖の菩提寺安立寺の墓所を継承し、東都における不白流茶道の家元として江戸千家七代を名のりました。
        <br>
        <image src="/assets/inside_gate2.jpg" class="inside_gate2-image">
      </p>

      
      <p class="info-text">
        <b>八代　一元斎不白</b>
        <br>
        <span class="font-small">
        蓮々斎の養嗣子として八代を継承し、大正から昭和の戦前までを江戸千家の当主として勤めました。岩手の南部藩、上越の高田藩、高知の土佐藩、久留米の有馬藩など、不白流の茶道が伝えられていた各地との繋がりを復活させてゆきました。
        <br>
        <image src="/assets/iemoto.jpg" class="iemoto-image">
      </p>


    
    </div>
    <div class="about-container2">
      <p class="info-text">
        <b>九代　名元庵宗雪</b>
        <br>
        <span class="font-small">
        一元斎の嗣子。病後は家族並びに社中の協力を得ながら、戦後の経済復興、文化の拡がりに乗って、江戸千家茶道の流儀を展げました。
      </p>

      <p class="info-text2">
        <b>十代（当代)　名心庵宗雪</b>
        <br>
        <span class="font-small">
        名元庵の嗣子。昭和四十年継承、今日に至っています。これからの茶家のあり方について工夫を重ねています。
      </p>


    
    </div>
    </section>

app/views/tweets/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="./stylesheets/index.css">
  </head>
  <body>
    
  <!--  コンテンツを一旦仮置きする  -->
  <!--   First block Start   -->
  <section id="first-block">
    <div class="title-container">
      <h1>茶道江戸千家の世界</h1>
      <h3>~ Geeksalon Webコース1期生 ~</h3>
    </div>
  </section>
  <!--   First block End   -->
  <!--   Second block Start   -->
  <section id="second-block">
    <p class="info-title">
        About me
    </p>
    <div class="about-container">
      <p class="info-text">
        <b>サークル: ESS</b>
        <br>
        <span class="font-small">
        英語会に所属しています。
        <br>
        たくさんのイベントがあって面白いです。
        <br>
        特に好きなのは、外人を英語でガイドすることです。
        </span>
      </p>

      <p class="info-text">
        <b>早稲田大学政治経済学部3年</b>
        <br>
        <span class="font-small">
        将来は外資系コンサルタント関係の仕事につきたいです。
        <br>
        なので、日々経営や経済の勉強をしています。
        <br>
        最近読んだ本では、ドラッカーの「マネジメント」が面白かったです。
        </span>
      </p>

      <p class="info-text">
        <b>趣味: サッカー</b>
        <br>
        <span class="font-small">
        6歳の頃からサッカーをずっとやっていました。
        <br>
        ポジションは特にフォワードをしています。好きな選手はリオネルメッシです。
        <br>
        大学になってからサッカーをする機会が減ってしまったのでとても残念です。
        </span>
      </p>
    </div>
  </section>
  <!--   Second block End   -->
  <!--   Third block Start   -->
  <section id="third-block">
    <p class="events-title">
      Recent Events
    </p>
    <div class="event-container">
      <div class="event">
      <img src='<%= asset_path('event1.jpg') %>'class="event-image"/>
        <p class="event-name">
          <span>11/23<br>関東大会</span>
          <br>
          <br>
          今年の秋は関東大会に出場します。<br>
          全16大学が参加し、<br>
          全国大会出場に向けて試合をします。<br>
          サッカー同好会は昨年度優勝し、<br>
          全国大会に出場しました。
        </p>
      </div>
      <div class="event">
        <p class="event-name">
          <span>12/25<br>クリスマスパーティー</span>
          <br>
          <br>
          サッカー同好会は毎年<br>
          クリスマスの日にパーティーをします<br>
          毎年部員の半数以上が参加し<br>
          ビンゴをやったり、ゲームをしたりして<br>
          一晩中楽しみます。
        </p>
        <img src='<%= asset_path('event3.jpg') %>'class="event-image"/>
      </div>
    </div>
  </section>
  <!--   Third block End   -->
  <!--  コンテンツはここまで  -->

    <footer>
      <p>Copyright © ○○○○ All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/tweets/tool.html.erb
<!--   First block Start   -->
  <section id="first-block2">
    <div class="title-container">
      <h1>茶道江戸千家の世界</h1>
      <h3>~ Geeksalon Webコース1期生 ~</h3>
    </div>
  </section>
  <!--   First block End   -->
  <!--   Second block Start   -->
  <section id="tool-block">
    <p class="info-title">
        About me
    </p>
    <div class="about-container">
      <div class="info-text">
      <img src='<%= asset_path('tea-bowl-slide.jpg') %>'width="350" heigh="100"/>
      </div>

      <div class="info-text2">
      <img src='<%= asset_path('tea-container-slide.jpg') %>'width="350" heigh="100"/>
      </div>

      
      <p class="info-text">
        
      <img src='<%= asset_path('tea-scoop-slide.jpg') %>'/width="350" heigh="100">
      </p>


    
    </div>
    <div class="about-container2">
      <p class="info-text">
      <img src='<%= asset_path('tea-whisk-slide.jpg') %>'width="350" heigh="100"/> 
      </p>

      <p class="info-text2">
      <img src='<%= asset_path('silk-skin-slide.jpg') %>'width="350" heigh="100"/>
      </p>

      <p class="info-text2">
      <img src='<%= asset_path('water-container-slide.jpg') %>'width="350" heigh="100"/>
      </p>
    
    </div>
    <div class="about-container2">
    <p class="info-text">
    <img src='<%= asset_path('waste-water-container-slide.jpg') %>'width="350" heigh="100"/> 
    </p>

    <p class="info-text2">
    <img src='<%= asset_path('lid-rest-slide.jpg') %>'width="350" heigh="100"/>
    </p>

    <p class="info-text2">
    <img src='<%= asset_path('ladle-slide.jpg') %>'width="350" heigh="100"/>
    </p>
    
   
  </div>
  <div class="about-container2">
   
    
    <p class="info-text2">
    <img src='<%= asset_path('kettle-slide.jpg') %>'width="600" heigh="200"/>
    </p>
  </div>
    </section>